name: ValerinUtils
version: "1.0-SNAPSHOT"
main: me.Mtynnn.valerinUtils.ValerinUtils
api-version: "1.21"
author: Mtynnn
description: Utilidades varias para ValerinSMP
softdepend: [PlaceholderAPI, Votifier, VotifierPlus]

commands:
  valerinutils:
    description: Comandos de administración de ValerinUtils
    usage: "/valerinutils reload"
    aliases: [vu, vutils]
    permission: valerinutils.admin
    permission-message: "&cNo tienes permiso para usar este comando."

  menuitem:
    description: Activa o desactiva tu item de menú
    usage: "/menuitem <on|off|toggle>"
    aliases: [menu]
